def Students():
    students=[
        {
            'id':1,
            'name':'raj',
            'Place':'Kannur',
            'mobile':7025301708,
            'email':'raj@gmail.com',
            'joindate':'7/11/2018'
        },
        {
            'id':2,
            'name':'dyu',
            'Place':'Kannur',
            'mobile':9946569297,
            'email':'dyu@gmail.com',
            'joindate':'7/11/2018'
        },
        {
            'id':3,
            'name':'sohna',
            'Place':'Kannur',
            'mobile':9895274069,
            'email':'soh@gmail.com',
            'joindate':'7/11/2018'
        },
        {
            'id':4,
            'name':'saanj'
            'Place':'Kannur',
            'mobile':9074186768,
            'email':'saanj@gmail.com',
            'joindate':'7/11/2018'
        },
        {
            'id':5,
            'name':'saif',
            'Place':'malappuram',
            'mobile':54647587893,
            'email':'saif@gmail.com',
            'joindate':'7/11/2018'
        },
        {
            'id':6,
            'name':'Akhil',
            'Place':'calicut',
            'mobile':345677880,
            'email':'ak@gmail.com',
            'joindate':'13/10/2018'
        },
        {
            'id':7,
            'name':'vineeth',
            'Place':'kannur',
            'mobile':945677885,
            'email':'vi@gmail.com',
            'joindate':'7/11/2018'
        },
        {
            'id':8,
            'name':'Arjun',
            'Place':'kannur',
            'mobile':995677880,
            'email':'ar@gmail.com',
            'joindate':'13/10/2018'
        },
        {
            'id':9,
            'name':'rinsha',
            'Place':'Payyannur',
            'mobile':999677880,
            'email':'ri@gmail.com',
            'joindate':'7/11/2018'
        },
        {
            'id':10,
            'name':'Deepthi',
            'Place':'calicut',
            'mobile':9746778880,
            'email':'dee@gmail.com',
            'joindate':'7/11/2018'
        }
    ]
    return students